pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REBUILD)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "Jarvis"
include ':app'

